src/objects/Project__c.object
<CustomObject>
    <description>Store Project Details like Start Date, End Date and project Code and Description</description>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Minutes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <label>Team Member</label>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Sheet__c</fullName>
        <label>Time Sheet</label>
        <referenceTo>Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timer_Start_Date_Time__c</fullName>
        <label>Timer Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timer_Started__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Timer Started</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TI-{00000}</displayFormat>
        <label>Time Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Sheet</relationshipLabel>
        <relationshipName>Time_Sheet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TS-{DD}{MM}{YYYY}{000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeEntries.cls
/**
*   Domain Class for Time Entries Object 
*   Extending sObjectDomain Class and Invoke override methods based on the Trigger State
*
**/

public with sharing class TimeEntries extends SObjectDomain{

    public TimeEntries(List<Time_Entry__c> sObjectList){
        // Domain classes are initialised with lists to enforce bulkification throughout
        super(sObjectList);
    }    
        
    public override void onBeforeInsert(){
        UpdateTimerMinutes(null); 
        AssignTeamMember();       
    }  
    
    public override void onBeforeUpdate(Map<Id,SObject> existingRecords){
         UpdateTimerMinutes(existingRecords);      
    }      
    
    public void StopTimer(SObjectUnitOfWork uow){    
        for(Time_Entry__c timeEntry : (List<Time_Entry__c>) Records){
            timeEntry.Timer_Started__c = false; 
            uow.registerDirty(timeEntry);
        }
    }
    
    
    public void StartTimer(SObjectUnitOfWork uow){    
        for(Time_Entry__c timeEntry : (List<Time_Entry__c>) Records){
            timeEntry.Timer_Started__c = true; 
            uow.registerDirty(timeEntry);
        }
    }    
        
    private void UpdateTimerMinutes(Map<Id,SObject> existingRecords) {        
        for(Time_Entry__c record: (List<Time_Entry__c>) Records)
        {   
            //Assign Old Record from Existing records
            Time_Entry__c oldRecord = new Time_Entry__c();   
            if(existingRecords != null){              
                oldRecord = (Time_Entry__c)existingRecords.get(record.id);
            }
            // Find the Diffrence if the Timer is Stoped and Add the Difference in Minutes Field
            if(!record.Timer_Started__c  && existingRecords != null && record.Timer_Started__c != oldRecord.Timer_Started__c
                && record.Timer_Start_Date_Time__c != null ){
                Long startDateTime = record.Timer_Start_Date_Time__c.getTime();
                Long endDateTimeLong = system.now().getTime();
                Long milliseconds = endDateTimeLong  - startDateTime;
                Long seconds = milliseconds / 1000;
                Long minutes = seconds / 60;
                Long hours = minutes / 60;
                Long days = hours / 24;  
                record.Minutes__c = record.Minutes__c + minutes;              
                record.Timer_Start_Date_Time__c = null; // Assign the Start Date to null 
            }else if(record.Timer_Started__c  && (existingRecords == null || record.Timer_Started__c != oldRecord.Timer_Started__c) && record.Timer_Start_Date_Time__c == null){
                // If timer is Started Assign the Start Date to Current Date time
                record.Timer_Start_Date_Time__c = system.now();
            }   
        
        }                                                               
    }

    private void AssignTeamMember() {  
        
        set<Id> timeSheetIdSet = new set<Id>();
        for(Time_Entry__c record: (List<Time_Entry__c>) Records){   
            if(record.Time_Sheet__c != null){
                timeSheetIdSet.add(record.Time_Sheet__c);
            }
        }
        
        map<Id,Time_Sheet__c> timeSheetMap = new map<Id,Time_Sheet__c>(new TimeSheetSelector().selectById(timeSheetIdSet));
        set<Id> projectIdSet = new Set<Id>();        
        for(Time_Sheet__c tSheet : timeSheetMap.values()){
            projectIdSet.add(tSheet.project__c);
        }
        
        map<Id,Id> projectCurrentTeamMembermap = new map<Id,Id>();
        projectCurrentTeamMembermap  = new TeamMemberSelector().getCurrentTeamMembersByProjects(projectIdSet);
        for(Time_Entry__c record: (List<Time_Entry__c>) Records){   
            if(record.Time_Sheet__c != null){
                record.Team_Member__c = projectCurrentTeamMembermap.get(timeSheetMap.get(record.Time_Sheet__c).project__c);
            }
        }        
        
    }

    public class Constructor implements SObjectDomain.IConstructable{
        public SObjectDomain construct(List<SObject> sObjectList){
            return new TimeEntries(sObjectList);
        }
    }
       
}