src/objects/Project__c.object
<CustomObject>
    <description>Store Project Details like Start Date, End Date and project Code and Description</description>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Sheet__c</fullName>
        <label>Time Sheet</label>
        <referenceTo>Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <formula>IF(LEN(TEXT(FLOOR( Minutes__c / 60))) &gt; 1,TEXT(FLOOR( Minutes__c / 60)),&quot;0&quot;&amp;TEXT(FLOOR( Minutes__c / 60)))&amp;&quot;:&quot;&amp;IF(LEN(TEXT(MOD( Minutes__c ,60))) &gt; 1,TEXT(MOD( Minutes__c ,60)),&quot;0&quot;&amp;TEXT(MOD( Minutes__c ,60)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time in Hours</label>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TI-{00000}</displayFormat>
        <label>Time Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Sheet</relationshipLabel>
        <relationshipName>Time_Sheet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TS-{DD}{MM}{YYYY}{000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeSheetController.cls
public with sharing class TimeSheetController {
    @AuraEnabled
    public static weekTimeReport getTimeEntries(date currentDate ) {        
        if(currentDate ==  null){
            currentDate = system.today();
        }
        
        Date startDate = currentDate.toStartOfWeek();
        list<Time_Entry__c> timeEntries = new list<Time_Entry__c>();
        weekTimeReport weekRprt;
        timeEntries = [select id,Employee__c,Date__c,Minutes__c,Time__c,Task__r.Name,Time_Sheet__r.Project__r.Name from Time_Entry__c 
                       where Employee__c =: userInfo.getUserId()];
        
        string totalHours ;
        decimal totalMinutes = 0;
        for(Time_Entry__c te: timeEntries ){
            if(te.Minutes__c != null){
                totalMinutes = totalMinutes+te.Minutes__c;
            }        
        }
        decimal hours = math.floor(totalMinutes /60);
        integer minuts = math.MOD(integer.valueOf(totalMinutes ),60);
        totalHours  = string.valueOf(hours) +':' +string.valueOf(minuts);        
        weekRprt = new weekTimeReport(totalHours,startDate ,timeEntries);
        
       return weekRprt ;
    } 
        
}