src/objects/Project__c.object
<CustomObject>
    <description>Store Project Details like Start Date, End Date and project Code and Description</description>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Sheet</relationshipLabel>
        <relationshipName>Time_Sheet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weekend_Date__c</fullName>
        <label>Weekending Date</label>
        <type>Date</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TS-{DD}{MM}{YYYY}{000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeSheetService.cls
/*
*
*
*/

global with sharing class TimeSheetService {       
    

    global static list<Time_Sheet__c> getTotalTimeSheetForEachWeek(date weekEndDate)
    {
          return new TimeSheetSelector().getTimeSheetByWeekEndDate(weekEndDate).values();                 
    }
    
    
    global static void createTimeSheetForProject(set<Id> projectIds)
    {
        // Create unit of work to capture work and commit it under one transaction
        SObjectUnitOfWork uow = new SObjectUnitOfWork(SERVICE_SOBJECTS);    
        for(Id projectId: projectIds){
            Time_Sheet__c tSheet = new Time_Sheet__c();
            tSheet.Project__c = projectId;
            tSheet.Weekend_Date__c = system.today().addDays(6);   
            uow.registerNew(tSheet);         
        } 
        uow.commitWork();                     
    }    
            
                
    // SObject's used by the logic in this service, listed in dependency order
    private static List<Schema.SObjectType> SERVICE_SOBJECTS = 
        new Schema.SObjectType[] { 
            Time_Sheet__c.SObjectType
            };  
}