src/objects/Project__c.object
<CustomObject>
    <description>Store Project Details like Start Date, End Date and project Code and Description</description>
    <fields>
        <fullName>Project_Code__c</fullName>
        <externalId>true</externalId>
        <label>Project Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <label>Team Member</label>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Sheet__c</fullName>
        <label>Time Sheet</label>
        <referenceTo>Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timer_Started__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Timer Started</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TI-{00000}</displayFormat>
        <label>Time Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Sheet</relationshipLabel>
        <relationshipName>Time_Sheet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Weekend_Date__c</fullName>
        <label>Weekending Date</label>
        <type>Date</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TS-{DD}{MM}{YYYY}{000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeSheetControllerTest.cls
/************************************************************************************

Author: Sai Sagar
Description: Test Class to test TimeSheetController

*************************************************************************************/
@isTest
public class TimeSheetControllerTest{
    


    @testSetup static void LoadDateForTimeEntries() {
        Project__c proj = new Project__c();
        proj.Name = 'Web Service';
        proj.Project_Code__c = 'PROJ1211';
        proj.projts__Project_Manager__c = userInfo.getUserId();        
        insert proj;                                
        
        Team_Member__c tMembr = new Team_Member__c();
        tMembr.projts__Billing_Rate__c = 100;
        tMembr.projts__Project__c = proj.id;
        tMembr.projts__Employee__c = userInfo.getUserId();
        insert tMembr;
        
        Task__c tsk = new Task__c();
        tsk.name = 'Development';
        insert tsk;
        
        Time_Sheet__c tSheet = new Time_Sheet__c();
        tSheet.Project__c = proj.Id; 
        tSheet.Weekend_Date__c = system.today().toStartOfWeek().addDays(6);
        tSheet.Status__c = 'Pending Approval';       
        insert tSheet;
        
        list<Time_Entry__c> timeEntryList = new list<Time_Entry__c>();
        
        for(integer i=0; i< 200; i++){
            Time_Entry__c entry = new Time_Entry__c();
            entry.Minutes__c = 122;
            entry.Time_Sheet__c = tSheet.id;  
            entry.Date__c = system.today(); 
            entry.Team_Member__c =  tMembr.id;  
            timeEntryList.add(entry);
        }
        insert timeEntryList ;   
    
    }    
    

    static testmethod void TestgetTimeEntries(){ 
        weekTimeReport  Report;
        
        test.StartTest();
            Report = TimeSheetController.getTimeEntries();
        test.StopTest();
        
        Date startDate = System.today().toStartOfWeek();
        system.assertEquals(Report.startDate,startDate);
    }


    static testmethod void TestgetProjectList(){ 
        List<Time_Sheet__c> timeSheetList;
        
        test.StartTest();
            timeSheetList = TimeSheetController.getProjectList();
        test.StopTest();
        system.assert(timeSheetList.size() == 1);
    }
    
    static testmethod void TestgetTaksList(){
    
        Project__c proj = new Project__c();
        proj.Name = 'Web Service';
        proj.Project_Code__c = 'PROJ1211';
        proj.projts__Project_Manager__c = userInfo.getUserId();        
        insert proj;                                
        
        Team_Member__c tMembr = new Team_Member__c();
        tMembr.projts__Billing_Rate__c = 100;
        tMembr.projts__Project__c = proj.id;
        tMembr.projts__Employee__c = userInfo.getUserId();
        insert tMembr;
        
        Task__c tsk = new Task__c();
        tsk.name = 'Development';
        tsk.Project__c = proj.Id;
        insert tsk;
        
        Time_Sheet__c tSheet = new Time_Sheet__c();
        tSheet.Project__c = proj.Id; 
        tSheet.Weekend_Date__c = system.today().addDays(6);
        tSheet.Status__c = 'Pending Approval';       
        insert tSheet;
             
        List<Task__c> taskList;
        
        test.StartTest();
            taskList = TimeSheetController.getTaksList(tSheet.id);
        test.StopTest();
        system.assert(taskList.size() == 1);
    }  
    
    
    static testmethod void TestcreateNewTimer(){
    
        Project__c proj = new Project__c();
        proj.Name = 'Web Service';
        proj.Project_Code__c = 'PROJ1211';
        proj.projts__Project_Manager__c = userInfo.getUserId();        
        insert proj;                                
        
        Team_Member__c tMembr = new Team_Member__c();
        tMembr.projts__Billing_Rate__c = 100;
        tMembr.projts__Project__c = proj.id;
        tMembr.projts__Employee__c = userInfo.getUserId();
        insert tMembr;
        
        Task__c tsk = new Task__c();
        tsk.name = 'Development';
        tsk.Project__c = proj.Id;
        insert tsk;
        
        Time_Sheet__c tSheet = new Time_Sheet__c();
        tSheet.Project__c = proj.Id; 
        tSheet.Weekend_Date__c = system.today().addDays(6);
        tSheet.Status__c = 'Pending Approval';       
        insert tSheet;             
        
        test.StartTest();
            TimeSheetController.createNewTimer(tSheet.id,tsk.Id);
        test.StopTest();
        
        List<Time_Entry__c>  entry = [Select id from Time_Entry__c where Time_Sheet__c =: tSheet.id AND Task__c =: tsk.Id];
        system.assert(entry.size() == 1);
    }  
    
    static testmethod void TestStopTimerTest(){
    
        Project__c proj = new Project__c();
        proj.Name = 'Web Service';
        proj.Project_Code__c = 'PROJ1211';
        proj.projts__Project_Manager__c = userInfo.getUserId();        
        insert proj;                                
        
        Team_Member__c tMembr = new Team_Member__c();
        tMembr.projts__Billing_Rate__c = 100;
        tMembr.projts__Project__c = proj.id;
        tMembr.projts__Employee__c = userInfo.getUserId();
        insert tMembr;
        
        Task__c tsk = new Task__c();
        tsk.name = 'Development';
        tsk.Project__c = proj.Id;
        insert tsk;
        
        Time_Sheet__c tSheet = new Time_Sheet__c();
        tSheet.Project__c = proj.Id; 
        tSheet.Weekend_Date__c = system.today().addDays(6);
        tSheet.Status__c = 'Pending Approval';       
        insert tSheet;             


        Time_Entry__c entry = new Time_Entry__c();
        entry.Timer_Started__c  = true;
        entry.Time_Sheet__c = tSheet.id;  
        entry.Date__c = system.today(); 
        entry.Team_Member__c =  tMembr.id;    
        insert entry;        
        
        test.StartTest();
            TimeSheetController.stopTimer(entry.id);
        test.StopTest();
        
        List<Time_Entry__c>  entryList = [Select id,Timer_Started__c   from Time_Entry__c where Id =: entry.id];
        system.assert(!entryList[0].Timer_Started__c  );
    }           
    

    static testmethod void TestStartTimerTest(){
    
        Project__c proj = new Project__c();
        proj.Name = 'Web Service';
        proj.Project_Code__c = 'PROJ1211';
        proj.projts__Project_Manager__c = userInfo.getUserId();        
        insert proj;                                
        
        Team_Member__c tMembr = new Team_Member__c();
        tMembr.projts__Billing_Rate__c = 100;
        tMembr.projts__Project__c = proj.id;
        tMembr.projts__Employee__c = userInfo.getUserId();
        insert tMembr;
        
        Task__c tsk = new Task__c();
        tsk.name = 'Development';
        tsk.Project__c = proj.Id;
        insert tsk;
        
        Time_Sheet__c tSheet = new Time_Sheet__c();
        tSheet.Project__c = proj.Id; 
        tSheet.Weekend_Date__c = system.today().addDays(6);
        tSheet.Status__c = 'Pending Approval';       
        insert tSheet;             


        Time_Entry__c entry = new Time_Entry__c();
        entry.Time_Sheet__c = tSheet.id;  
        entry.Date__c = system.today(); 
        entry.Team_Member__c =  tMembr.id;    
        insert entry;        
        
        test.StartTest();
            TimeSheetController.startTimer(entry.id);
        test.StopTest();
        
        List<Time_Entry__c>  entryList = [Select id,Timer_Started__c   from Time_Entry__c where Id =: entry.id];
        system.assert(entryList[0].Timer_Started__c  );
    }    
}