src/objects/Project__c.object
<CustomObject>
    <description>Store Project Details like Start Date, End Date and project Code and Description</description>
    <fields>
        <fullName>Project_Code__c</fullName>
        <externalId>true</externalId>
        <label>Project Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <label>Team Member</label>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Sheet__c</fullName>
        <label>Time Sheet</label>
        <referenceTo>Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timer_Start_Date_Time__c</fullName>
        <label>Timer Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timer_Started__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Timer Started</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TI-{00000}</displayFormat>
        <label>Time Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Sheet</relationshipLabel>
        <relationshipName>Time_Sheet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Weekend_Date__c</fullName>
        <label>Weekending Date</label>
        <type>Date</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TS-{DD}{MM}{YYYY}{000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeEntryTriggerHandlerTest.cls
/************************************************************************************

Author: Sai Sagar
Description: Test Class to test TimeEntryTrigger 

*************************************************************************************/
@isTest
public class TimeEntryTriggerHandlerTest{
    
    /*  Create New Time Entry Record -- Start Timer
     */ 
    static testmethod void TestUpdateTimerMinutesInsert(){
        
        Project__c proj = new Project__c();
        proj.Name = 'Web Service';
        proj.Project_Code__c = 'PROJ1211';
        proj.projts__Project_Manager__c = userInfo.getUserId();        
        insert proj;                                
        
        Team_Member__c tMembr = new Team_Member__c();
        tMembr.projts__Billing_Rate__c = 100;
        tMembr.projts__Project__c = proj.id;
        tMembr.projts__Employee__c = userInfo.getUserId();
        insert tMembr;
        
        Task__c tsk = new Task__c();
        tsk.name = 'Development';
        insert tsk;
        
        Time_Sheet__c tSheet = new Time_Sheet__c();
        tSheet.Project__c = proj.Id; 
        tSheet.Weekend_Date__c = system.today().addDays(6);
        tSheet.Status__c = 'Pending Approval';       
        insert tSheet;
        
        test.StartTest();
            Time_Entry__c entry = new Time_Entry__c();
            entry.Timer_Started__c  = true;
            entry.Time_Sheet__c = tSheet.id;  
            entry.Date__c = system.today(); 
            entry.Team_Member__c =  tMembr.id;    
            insert entry;
        test.StopTest();   
        
        Time_Entry__c StartTime = [Select id,Timer_Start_Date_Time__c from Time_Entry__c  where id =: entry.Id];
        system.assert(StartTime.Timer_Start_Date_Time__c != null);
        
             
    }
    


    /*  Create New Time Entry Record -- Start Timer
     */ 
    static testmethod void TestUpdateTimerMinutesInsertBulk(){
        
        Project__c proj = new Project__c();
        proj.Name = 'Web Service';
        proj.Project_Code__c = 'PROJ1211';
        proj.projts__Project_Manager__c = userInfo.getUserId();        
        insert proj;                                
        
        Team_Member__c tMembr = new Team_Member__c();
        tMembr.projts__Billing_Rate__c = 100;
        tMembr.projts__Project__c = proj.id;
        tMembr.projts__Employee__c = userInfo.getUserId();
        insert tMembr;
        
        Task__c tsk = new Task__c();
        tsk.name = 'Development';
        insert tsk;
        
        Time_Sheet__c tSheet = new Time_Sheet__c();
        tSheet.Project__c = proj.Id; 
        tSheet.Weekend_Date__c = system.today().addDays(6);
        tSheet.Status__c = 'Pending Approval';       
        insert tSheet;
        
        test.StartTest();
            list<Time_Entry__c> timeEntryList = new list<Time_Entry__c>();
            
            for(integer i=0; i< 200; i++){
                Time_Entry__c entry = new Time_Entry__c();
                entry.Timer_Started__c  = true;
                entry.Time_Sheet__c = tSheet.id;  
                entry.Date__c = system.today(); 
                entry.Team_Member__c =  tMembr.id;  
                timeEntryList.add(entry);
            }
            insert timeEntryList ;
        test.StopTest();   
        
        List<Time_Entry__c> StartTimeList = [Select id,Timer_Start_Date_Time__c from Time_Entry__c  where id =: timeEntryList];
        for(Time_Entry__c StartTime: StartTimeList ){
            system.assert(StartTime.Timer_Start_Date_Time__c != null);
        }        
        
             
    }    
    
   /*  Update Time Entry Record - Stop Timer
    */ 
    
    static testmethod void TestUpdateTimerMinutesUpdate(){
        
        Project__c proj = new Project__c();
        proj.Name = 'Web Service';
        proj.Project_Code__c = 'PROJ1211';
        proj.projts__Project_Manager__c = userInfo.getUserId();        
        insert proj;                                
        
        Team_Member__c tMembr = new Team_Member__c();
        tMembr.projts__Billing_Rate__c = 100;
        tMembr.projts__Project__c = proj.id;
        tMembr.projts__Employee__c = userInfo.getUserId();
        insert tMembr;
        
        Task__c tsk = new Task__c();
        tsk.name = 'Development';
        insert tsk;
        
        Time_Sheet__c tSheet = new Time_Sheet__c();
        tSheet.Project__c = proj.Id; 
        tSheet.Weekend_Date__c = system.today().addDays(6);
        tSheet.Status__c = 'Pending Approval';       
        insert tSheet;
        
        
        Time_Entry__c entry = new Time_Entry__c();
        entry.Timer_Started__c  = true;
        entry.Time_Sheet__c = tSheet.id;  
        entry.Date__c = system.today(); 
        entry.Team_Member__c =  tMembr.id;    
        insert entry;
        
        
        test.StartTest(); 
            entry.Timer_Started__c  = false; 
            update entry;          
        test.StopTest();   
        
        Time_Entry__c StartTime = [Select id,Timer_Start_Date_Time__c from Time_Entry__c  where id =: entry.Id];
        system.assert(StartTime.Timer_Start_Date_Time__c == null);
        
             
    }    
        
}