src/objects/Project__c.object
<CustomObject>
    <description>Store Project Details like Start Date, End Date and project Code and Description</description>
    <label>Project</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Sheet</relationshipLabel>
        <relationshipName>Time_Sheet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weekend_Date__c</fullName>
        <label>Weekending Date</label>
        <type>Date</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TS-{DD}{MM}{YYYY}{000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeSheetSelector.cls
/**
 *  Selector Class to Construct the Dynamic Query for Time Sheet (Sobject)
 **/
 
public class TimeSheetSelector extends SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList(){    
        return new List<Schema.SObjectField> { 
                                                Time_Sheet__c.Weekend_Date__c,
                                                Time_Sheet__c.Project__c
                                             };
    }

    public Schema.SObjectType getSObjectType(){
        return Time_Sheet__c.sObjectType;
    }

    /**
     * Queries Time Entry records Ids
     **/ 
    public List<Time_Sheet__c> selectById(Set<ID> idSet){
        return (List<Time_Sheet__c>) selectSObjectsById(idSet);
    }
    
    /**
     * Queries Time Sheet records and return map of Id and record based on Week End Date
     **/        
    public Map<Id,Time_Sheet__c> getTimeSheetByWeekEndDate(date weekEndDate){        
        String query = String.format('select {0},{2} FROM {1} WHERE Weekend_Date__c =: weekEndDate', 
                    new List<String>{
                        getFieldListString(),
                        getSObjectName(),
                        'Project__r.Name'
                    });      
        return new map<Id,Time_Sheet__c>((List<Time_Sheet__c>) Database.query(query));  
    }
    
}